CREATE DATABASE IF NOT EXISTS TP2020_ENCRYPTION;

CREATE TABLE IF NOT EXISTS TP2020_ENCRYPTION.OPE_Example(
    name VARCHAR(20),
    salaryOPE BIGINT UNSIGNED NOT NULL,
    PRIMARY KEY(name));

CREATE TABLE IF NOT EXISTS TP2020_ENCRYPTION.HOMOMORPHIC_Example(
    name VARCHAR(20),
    salaryOPE BIGINT UNSIGNED NOT NULL,
    salaryHOMOMORPHIC BLOB NOT NULL,
    PRIMARY KEY(name));

CREATE USER IF NOT EXISTS 'encryption'@'localhost' IDENTIFIED by 'encryption2020';
GRANT all privileges on TP2020_ENCRYPTION.* to 'encryption'@'localhost';
FLUSH privileges;